Add annotation to benchmark increase errors

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -92,5 +92,14 @@ jobs:
             | add
           ' | tee "${{ runner.temp	}}/comparison"
 
+      # TODO add informative annotation https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
       - name: Error on unacceptable benchmark increases
-        run: jq -e 'false == any( .[] ; .change_pct > 2)' "${{ runner.temp	}}/comparison"
+        run: |
+          jq -e 'false == any( .[] ; .change_pct > 2)' "${{ runner.temp	}}/comparison"
+          EXIT_CODE = $?
+          if [ $EXIT_CODE -ne 0 ]
+          then
+            ANNOTATION = $( jq --argfile prev prev --argfile curr curr -n -r '$prev | [keys[] | {"\(.)":{ prev:$prev[.], curr:$curr[.], change:($curr[.]-$prev[.]), change_pct:(($curr[.]/$prev[.]-1)*100) }}] | add | [to_entries[] | select(.value.change_pct>2) | "\(.key) increased from \(.value.prev) to \(.value.curr)"] | join(", ")' )
+            echo "::error file=benchmarks/${{ matrix.benchmark }},title=Benchmark regression::$ANNOTATION"
+          fi
+          (exit $EXIT_CODE)
